shamefullyHoist: true
allowBuilds:
  better-sqlite3: true
  workerd: true
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  esbuild: false
  unrs-resolver: false
  vue-demi: false
  sharp: true
  typeit: true
